### ISSUE TITLE
Add Data Science to Competences

### ISSUE THREAD

**Issue by agosiewska** [agosiewska/data-driven-resume#6]

**Comment by MarcinKosinski** [comment]
I would write Machine Learning as some recruiters either
a) do not imply knowledge of Machine Learning based on knowledge of Data Science because they don't know what both terms mean
b) are over-educated and see a huge difference between Data Science and Machine Learning and do not imply knowledge of one from another

cc @agosiewska

**Comment by agosiewska** [comment]
Thanks :)
